Add undo functionality
rama56/CardGame904 pull request #1
Opened 2020-04-18 14:33 UTC by kckrithika

2020-04-18 15:16 UTC, rama56 requested changes

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
> +app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes=30)
Why 30 minutes? What does this do?

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
> +app.secret_key = os.urandom(16)
what is this 16?

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
> +    session['history'] = [jsonpickle.encode(game_state)]
Use json_respone from above line.

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
> +@cross_origin(supports_credentials=True)
What is this for? I thought CORS issue was resolved last time.

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
>      return game_state
Convert to JSON before sending to the client.

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
>      game_state = GameState()
This is wrong. This is 'new game' functionality.

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
> +        return ""
What does the client do with this empty string?

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
>      json_response = jsonpickle.encode(game_state)
Move this line to after  "game_state.alter_state()" and use it in the subsequent line to append to history.

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
> +    session['history'] = []
Why assign it an empty list?

2020-04-18 15:16 UTC, rama56 commented on GameHost/app.py
> +def undo():
If possible, add an Unit Test.

2020-04-19 15:48 UTC, kckrithika commented on GameHost/app.py
> +app.config['PERMANENT_SESSION_LIFETIME'] = timedelta(minutes=30)
It retains the session for 30 minutes

2020-04-19 15:48 UTC, kckrithika commented on GameHost/app.py
> +app.secret_key = os.urandom(16)
16 digit secret key, made of random characters

2020-04-19 15:55 UTC, kckrithika commented on GameHost/app.py
> +@cross_origin(supports_credentials=True)
CORS issue was solved by allowing access to specified resources from specified origins. To enable sessions, flask requires the client to send credentials. That's why the 'xmlhttp.withCredentials' was set in the front end code. To receive the credentials, we need to allow it explicitly.

2020-04-19 16:05 UTC, kckrithika commented on GameHost/app.py
> +        return ""
client is unable to parse this. It's not handled gracefully. Will make the UI handle it gracefully in the next cut. For now, it does not affect any of the existing functionalities

2020-04-21 09:41 UTC, rama56 commented on GameHost/app.py
> +def undo():
Also add into README.md the issues faced and how it were solved.

2020-04-30 11:03 UTC, merged